// Die Seiten des Mockup-Satzes: eine Wahrheit für Galerie, Geräteansicht und Bildschirmfotos.
// [Datei, Nummer, Titel, Untertitel, Oberfläche (allgemein|handy|rechner), Staffel]
const SEITEN = [
  ["g01-marken.html", "G01", "Marken", "Farben hell und dunkel, Schriften, Schatten, gemessene Kontraste", "allgemein", 1],
  ["g02-zeichen.html", "G02", "Zeichen", "Code-Stempel, Erscheinungsbild, Mengentext, Score-Marken, Markenzeichen", "allgemein", 1],
  ["h01-bausteine.html", "H01", "Bausteine Handy", "Alle Bausteine der Handy-Oberfläche mit ihren Zuständen", "handy", 1],
  ["h02-anmeldung.html", "H02", "Anmeldung", "Adresse und Kennwort, Marke oben", "handy", 1],
  ["h03-anmeldung-zweiter-schritt.html", "H03", "Anmeldung: zweiter Schritt und Sperre", "Sechs Ziffern, Wiederherstellungscode, Sperre mit Wartezeit", "handy", 1],
  ["h04-start.html", "H04", "Start", "Kennzahlen, zuletzt genutzte Orte, Hauptbereiche", "handy", 1],
  ["h05-start-erststart.html", "H05", "Start beim ersten Mal", "Alles leer, eine Handlung: ersten Ort anlegen", "handy", 1],
  ["h06-behaelter.html", "H06", "Behälter", "Kühlschrank: Zusammenfassung, Neu-Streifen, Inhalt", "handy", 1],
  ["h07-behaelter-lang.html", "H07", "Behälter mit vielen Einträgen", "Bücherregal: Filter nach Kategorie, 25 von 50, Titel im Kopf", "handy", 1],
  ["h08-behaelter-leer.html", "H08", "Behälter leer", "Leerzustand mit einer Handlung", "handy", 1],
  ["h09-pfad-und-aktionen.html", "H09", "Pfad-Blatt und Aktions-Blatt", "Wo liegt es, und was lässt sich damit tun", "handy", 1],
  ["h10-eintrag-verbrauchsgut.html", "H10", "Eintrag: Verbrauchsgut", "Geschirrtabs: Mengenblock, Packungen, Verlauf, Codes unten", "handy", 1],
  ["h11-eintrag-einzelstueck.html", "H11", "Eintrag: Einzelstück", "Bohrmaschine: Bilder, Eigenschaften, kein Mengenblock", "handy", 1],
  ["h12-eintrag-lebensmittel.html", "H12", "Eintrag: Lebensmittel", "Milch: Icon statt Foto, zwei Haltbarkeiten, Score-Marken", "handy", 1],
  ["h16-bewegen.html", "H16", "Bewegen", "Ziel wählen: zuletzt genutzte Orte, Suche, Baum Ebene für Ebene", "handy", 1],
  ["h22-anlegen-schnell.html", "H22", "Anlegen, schnell", "Name, Ort, Ding oder Behälter, Speichern und nächstes", "handy", 1],
  ["h23-anlegen-mit-feldern.html", "H23", "Anlegen mit Feldern", "Menge, Kategorie, Felder der Kategorie, ein Feldfehler", "handy", 1],
  ["h24-datumsfeld.html", "H24", "Datumsfeld", "Tippen oder Kalender, Deutung in Worten", "handy", 1],
  ["h25-wahl-blatt.html", "H25", "Wahl-Blatt", "Kategorie wählen: Suche, große Zeilen, mehrere möglich", "handy", 1],
  ["h26-foto-was-ist-das.html", "H26", "Foto: Was ist das?", "Nach der Aufnahme: neuer Eintrag, zuordnen oder ablegen; Serie", "handy", 2],
  ["h27-foto-zuordnen.html", "H27", "Foto zuordnen", "Eintrag wählen: zuerst der aktuelle Ort, sonst Suche", "handy", 2],
  ["h40-bearbeiten.html", "H40", "Bearbeiten", "Übersicht der Bereiche, je Bereich ein kurzes Blatt", "handy", 1],
  ["h41-erscheinungsbild.html", "H41", "Erscheinungsbild", "Bild, Icon oder nichts; Farbton; Vorschau", "handy", 1],
  ["h42-loeschen.html", "H42", "Löschen", "Mit Inhalt oder Inhalt in die Ablage, Halten", "handy", 1],
  ["h49-zustaende.html", "H49", "Zustände", "Getrennt, neue Fassung, Laden, Sitzung abgelaufen", "handy", 1],
  ["h52-code-unbekannt.html", "H52", "Code nicht vergeben oder fremd", "Genau eine nächste Handlung", "handy", 1],
  ["h13-menge-verbrauchen.html", "H13", "Menge verbrauchen", "Blatt mit Inhalt oder ganzer Packung, schnellen Mengen und Grund", "handy", 2],
  ["h14-menge-einkaufen-zaehlen.html", "H14", "Menge ändern: Einkaufen und Zählen", "Zwei Blätter, die Wahlreihe wechselt dazwischen", "handy", 2],
  ["h15-meldung-rueckgaengig.html", "H15", "Meldung und Rückgängig", "Bestätigung mit Rückgängig, darunter eine Fehlermeldung", "handy", 2],
  ["h17-scanner-einbuchen.html", "H17", "Scanner: Einbuchen", "Zielort, Anzahl für den nächsten Scan, Ergebnis mit Rückgängig, Protokoll darunter", "handy", 2],
  ["h18-scanner-verbrauchen.html", "H18", "Scanner: Verbrauchen", "Ein Scan bucht eine Packung ab; Leeres bucht nichts", "handy", 2],
  ["h19-scanner-behaelter.html", "H19", "Scanner: Behälter gescannt", "Das Etikett eines Behälters setzt das Ziel", "handy", 2],
  ["h20-scanner-unbekannt.html", "H20", "Scanner: Strichcode unbekannt", "Anlegen und einbuchen in einem Blatt", "handy", 2],
  ["h21-scanner-code-tippen.html", "H21", "Scanner: Code tippen", "Ohne Kamerarecht, mit Deutung der Eingabe", "handy", 2],
  ["h28-park.html", "H28", "Ablage", "Was noch keinen Ort hat; je Zeile ein Knopf zum Bewegen", "handy", 2],
  ["h29-suche.html", "H29", "Suche", "Im Lager oder im Katalog, Treffer mit Code, Ort und Menge", "handy", 2],
  ["h30-verbrauch.html", "H30", "Verbrauch", "Je Verbrauchsgut eine Karte mit einem Mengenknopf", "handy", 2],
  ["h31-einkaufsliste.html", "H31", "Einkaufsliste", "Unter dem Mindestbestand und aufgebraucht, abhaken und einbuchen", "handy", 2],
  ["h32-haltbarkeit.html", "H32", "Haltbarkeit", "Abgelaufen und bald fällig, Vorschau 7, 14 oder 30 Tage", "handy", 2],
  ["h33-fotos.html", "H33", "Fotos", "Fotos eines Eintrags: Titelbild, Drehen, Entfernen mit Halten, Hinzufügen", "handy", 2],
  ["h34-katalog.html", "H34", "Katalog", "Produkte mit Bestand, Suche nach Name oder Strichcode", "handy", 2],
  ["h35-produkt.html", "H35", "Produkt", "Milch: Bestand je Ort, Zählweise, Strichcodes, Eigenschaften", "handy", 2],
  ["h36-bildbetrachter.html", "H36", "Bildbetrachter", "Dunkle Vollfläche, das Bild immer ganz; Drehen, Blättern", "handy", 2],
  ["h37-eintrag-foto-hinzufuegen.html", "H37", "Eintrag: Foto hinzufügen", "Schlanker Foto-Knopf unter den Bildern, Meldung mit Rückgängig", "handy", 2],
  ["h43-packungen.html", "H43", "Packungen", "Käufe eines Eintrags, Entsorgen mit Halten", "handy", 2],
  ["h48-mehr.html", "H48", "Mehr", "Listen, Katalog, Thema, Rechner-Ansicht, Abmelden", "handy", 2],
  ["h53-scanner-auswahl.html", "H53", "Scanner: Auswahl und fremdes Etikett", "Mehrere Orte zur Wahl; fremder Haushalt als Hinweis", "handy", 2],
  ["h54-suche-leer.html", "H54", "Suche ohne Treffer", "Leerzustand mit einer Handlung: anlegen", "handy", 2],
  ["h55-einkaufsliste-leer.html", "H55", "Einkaufsliste leer", "Nichts fehlt, eine Handlung: zum Lager", "handy", 2],
  ["r01-bausteine.html", "R01", "Bausteine Rechner", "Alle Bausteine der Rechner-Oberfläche mit ihren Zuständen", "rechner", 1],
  ["r02-anmeldung.html", "R02", "Anmeldung", "Kennwort, zweiter Schritt, Sperre", "rechner", 1],
  ["r03-lager-start.html", "R03", "Lager: Start", "Kennzahlen, Hauptbereiche, zuletzt bewegt", "rechner", 1],
  ["r04-behaelter-lesen.html", "R04", "Behälter lesen", "Kühlschrank: Inhalt als Karten, Zählung nach Kategorien", "rechner", 1],
  ["r05-behaelter-bearbeiten.html", "R05", "Behälter bearbeiten", "Bearbeiten an, Mehrfachauswahl, Auswahlleiste", "rechner", 1],
  ["r06-gegenstand-lesen.html", "R06", "Gegenstand lesen", "Geschirrtabs: Mengenblock, Packungen, Eigenschaften, Codes", "rechner", 1],
  ["r07-gegenstand-bearbeiten.html", "R07", "Gegenstand bearbeiten", "Name im Text, Felder, Kategorien, Aktionsleiste", "rechner", 1],
  ["r08-huelle-eingeklappt.html", "R08", "Hülle eingeklappt", "Seitenleiste als Icon-Spalte, Anfasser beim Ziehen", "rechner", 1],
  ["r09-baum-zustaende.html", "R09", "Baum: Treffer, Ziehziel, leer", "Suche im Baum, Ziehen mit Ziel, Anlegezeile", "rechner", 1],
  ["r10-fenster-anlegen.html", "R10", "Fenster: Anlegen mit Feldern", "Ort, Kategorien, Menge, Felder der Kategorie", "rechner", 1],
  ["r11-fenster-bewegen.html", "R11", "Fenster: Bewegen", "Ziel suchen oder im Baum wählen, zuletzt genutzte Orte", "rechner", 1],
  ["r13-fenster-loeschen.html", "R13", "Fenster: Löschen", "Mit Inhalt oder in die Ablage, Halten", "rechner", 1],
  ["r14-fenster-erscheinungsbild.html", "R14", "Fenster: Erscheinungsbild", "Bild, Icon oder nichts; Farbton; Vorschau", "rechner", 1],
  ["r15-bildbetrachter.html", "R15", "Bildbetrachter", "Dunkle Vollfläche über dem Eintrag; Blättern, Drehen, Titelbild", "rechner", 2],
  ["r43-zustaende.html", "R43", "Zustände", "Getrennt, neue Fassung, Laden, Fehler beim Laden", "rechner", 1],
  ["r44-formularfehler.html", "R44", "Felder und Formularfehler", "Prüfungen der Felder mit Deutung und Fehlertext", "rechner", 1],
  ["r12-fenster-menge.html", "R12", "Fenster: Menge ändern", "Verbrauchen, Einkaufen, Zählen; Zählen setzt den Bestand", "rechner", 2],
  ["r19-suche.html", "R19", "Suche", "Treffer in der Mittelspalte, gewählter Treffer rechts", "rechner", 2],
  ["r20-katalog.html", "R20", "Katalog", "Produkt lesen: im Lager, Strichcodes, Eigenschaften, Zählweise", "rechner", 2],
  ["r21-katalog-bearbeiten.html", "R21", "Katalog bearbeiten", "Name, Marke, Zählweise, Strichcodes; Löschen gesperrt", "rechner", 2],
  ["r22-katalog-leer.html", "R22", "Katalog leer", "Leerzustand mit einer Handlung", "rechner", 2],
  ["r23-einkaufsliste.html", "R23", "Einkaufsliste", "Abhaken und gesammelt einbuchen", "rechner", 2],
  ["r24-haltbarkeit.html", "R24", "Haltbarkeit", "Fällige Packungen der nächsten 7, 14 oder 30 Tage", "rechner", 2],
  ["r25-bilder-bearbeiten.html", "R25", "Bilder bearbeiten", "Im Bearbeiten: Bild hinzufügen, drehen, Titelbild, entfernen", "rechner", 2],
  ["r29-kategorien.html", "R29", "Kategorien", "Verhalten dreiwertig, Bausteine, Felder, Wirkungsvorschau", "rechner", 2],
  ["r42-scanner-schublade.html", "R42", "Scanner-Schublade", "Einbuchen am Rechner mit Anzahl für den nächsten Scan, Protokoll und unbekanntem Code", "rechner", 2],
  ["r45-fenster-einkaufen.html", "R45", "Fenster: Einkaufen", "Anzahl, Haltbar bis, Preis, Kaufdatum", "rechner", 2],
  ["h38-vorgaenge.html", "H38", "Vorgänge", "Läuft, wartet auf den KI-Rechner, fertig, gescheitert", "handy", 3],
  ["h39-wiegen.html", "H39", "Wiegen", "Wert der Waage, Leergewicht, Stückgewicht, Ergebnis", "handy", 3],
  ["h44-anreichern-suche.html", "H44", "Anreichern: Bereich und Treffer", "Bereich wählen, Strichcode oder Name, Treffer der Quellen", "handy", 3],
  ["h45-anreichern-vorschau.html", "H45", "Anreichern: Vorschau je Feld", "Jetzt und Vorschlag mit Kästchen, Herkunft je Wert", "handy", 3],
  ["h46-hilfe.html", "H46", "Hilfe", "Vollblatt mit Suche, Themen und offenem Artikel", "handy", 3],
  ["h47-ki-vorschlag.html", "H47", "Vorschlag der KI", "Nach einem Foto: erkannte Felder einzeln übernehmen", "handy", 3],
  ["h50-erinnerungen.html", "H50", "Erinnerungen", "Überfällig, bald, später; Erledigt", "handy", 3],
  ["h51-einstellungen.html", "H51", "Einstellungen", "Konto, Darstellung, dieses Gerät, Version", "handy", 3],
  ["h56-verbrauchsplan.html", "H56", "Verbrauchsplan", "Reichweite, heute offen, Plan einrichten", "handy", 3],
  ["h57-codes-gross.html", "H57", "Codes groß", "QR-Code oder Strichcode zum Abscannen", "handy", 3],
  ["h58-aufraeumen-vorschau.html", "H58", "Eigenschaften aufräumen", "Vorher und nachher je Zeile, einzeln übernehmen", "handy", 3],
  ["h60-erinnerungen-eintrag.html", "H60", "Erinnerungen am Eintrag", "Liste am Eintrag, Blatt Erinnerung anlegen", "handy", 3],
  ["h66-zeile-aktionen.html", "H66", "Aktionen an einer Zeile", "Langes Drücken: Alltagsknöpfe, Öffnen, Bewegen", "handy", 4],
  ["h67-eigene-eigenschaft.html", "H67", "Eigene Eigenschaft", "Feld nur für diesen Eintrag: neu oder vorhanden, entfernen", "handy", 4],
  ["h68-foto-erkennen.html", "H68", "Foto erkennen", "Gespeicherte Fotos wählen, weitere nur zum Erkennen dazu", "handy", 4],
  ["h69-info-modus.html", "H69", "Info-Modus", "Blau markiert, was erklärt ist; Tippen öffnet die Erklärung", "handy", 4],
  ["h70-scanner-umraeumen.html", "H70", "Scanner: Umräumen", "Behälter scannen, dann wandert jeder Scan dorthin", "handy", 4],
  ["h71-ausgaben-und-wert.html", "H71", "Ausgaben und Wert", "Ausgaben je Monat, Wert je Behälter, Preisverlauf", "handy", 4],
  ["h72-verleihen.html", "H72", "Verleihen", "An wen, zurück bis, Notiz; Namen zum Antippen", "handy", 4],
  ["h74-sorte.html", "H74", "Sorte ändern", "Raum, Behälter oder Ding, auch nachträglich", "handy", 4],
  ["h73-scanner-haltbarkeit.html", "H73", "Scanner: Haltbarkeit nachtragen", "Kamera öffnet sofort, Datum im Blatt prüfen, übernehmen", "handy", 4],
  ["h65-auswahl-behaelter.html", "H65", "Auswahl im Behälter", "Mehrere Einträge antippen und gemeinsam bewegen", "handy", 4],
  ["h64-zielort-waehlen.html", "H64", "Zielort wählen", "Wohin Neues aus dem Scanner kommt, mit zuletzt genutzten Orten", "handy", 4],
  ["h63-inhalt-ordnen.html", "H63", "Inhalt ordnen", "Reihenfolge, Archiv und Kategorie für den Inhalt eines Behälters", "handy", 4],
  ["h62-zuletzt-bewegt.html", "H62", "Zuletzt bewegt", "Bewegungen des Haushalts, unter Mehr", "handy", 4],
  ["h61-fuellstand.html", "H61", "Füllstand", "Pegel angebrochener Packungen mit dem Finger ziehen", "handy", 4],
  ["h59-verkauf.html", "H59", "Verkauf", "Titel, Zustand, Preis, Beschreibung, Text kopieren", "handy", 3],
  ["r16-anreichern.html", "R16", "Anreichern", "Fenster mit Bereich, Treffer und Vorschau je Feld", "rechner", 3],
  ["r17-ki-vorschau.html", "R17", "Vorschlag der KI", "Eigenschaften aufräumen: vorher und nachher", "rechner", 3],
  ["r18-vorgaenge-schublade.html", "R18", "Vorgänge", "Schublade mit laufenden und beendeten Vorgängen", "rechner", 3],
  ["r26-erinnerungen.html", "R26", "Erinnerungen", "Tabelle nach Fälligkeit mit Filter", "rechner", 3],
  ["r27-park-bereich.html", "R27", "Ablage", "Was noch keinen Ort hat, Auswahl einsortieren", "rechner", 3],
  ["r28-verkauf.html", "R28", "Verkauf", "Fenster mit Titel, Zustand, Preis, Beschreibung", "rechner", 3],
  ["r30-kategorie-felder.html", "R30", "Kategorie: Felder", "Felder und Regeln bearbeiten, Löschen", "rechner", 3],
  ["r31-einstellungen-konto.html", "R31", "Einstellungen: Konto", "Name, Adresse, Haushalt, Kennwort", "rechner", 3],
  ["r32-einstellungen-sicherheit.html", "R32", "Einstellungen: Sicherheit", "Zweiter Schritt, Sitzungen", "rechner", 3],
  ["r33-einstellungen-darstellung.html", "R33", "Einstellungen: Darstellung und Geräte", "Thema, Start, Waage", "rechner", 3],
  ["r34-verwaltung-konten.html", "R34", "Verwaltung: Konten", "Konten, Haushalte, Konto anlegen", "rechner", 3],
  ["r35-verwaltung-anbindungen.html", "R35", "Verwaltung: Anbindungen", "Quellen, KI-Rechner, Zwischenspeicher", "rechner", 3],
  ["r36-verwaltung-protokoll.html", "R36", "Verwaltung: Protokoll", "Suche, Stufe, seitenweise", "rechner", 3],
  ["r37-verwaltung-zuordnungen.html", "R37", "Verwaltung: Zuordnungen und Formate", "Quellfeld zu Zielfeld, Anzeigeformate", "rechner", 3],
  ["r38-verwaltung-sicherungen.html", "R38", "Verwaltung: Sicherungen", "Geprüfte Sicherungen, jetzt sichern, zurückspielen", "rechner", 3],
  ["r39-hilfefenster.html", "R39", "Hilfefenster", "Schwebend über dem Lager, mit Suche", "rechner", 3],
  ["r40-info-modus.html", "R40", "Info-Modus", "Markierte Elemente erklären sich beim Klick", "rechner", 3],
  ["r41-etiketten.html", "R41", "Etiketten", "Bogen mit Druckvorschau", "rechner", 3],
  ["r46-fenster-wiegen.html", "R46", "Fenster: Wiegen", "Wert der Waage, Ergebnis, Bestand festhalten", "rechner", 3],
  ["r47-verbrauchsplan.html", "R47", "Verbrauchsplan", "Plan am Eintrag, Fenster Plan einrichten", "rechner", 3],
  ["r48-erinnerungen-eintrag.html", "R48", "Erinnerungen am Eintrag", "Tabelle am Eintrag, Fenster Erinnerung anlegen", "rechner", 3],
  ["r56-verwaltung-uebersicht.html", "R56", "Verwaltung: Übersicht", "Bestand, Dienst, letzte Sicherung auf einen Blick", "rechner", 4],
  ["r57-verwaltung-eintraege.html", "R57", "Verwaltung: Einträge", "Mengen je Haushalt, keine Inhalte", "rechner", 4],
  ["r58-verwaltung-bilder.html", "R58", "Verwaltung: Bilder", "Bilder und Speicher je Haushalt, jetzt aufräumen", "rechner", 4],
  ["r60-verleihen.html", "R60", "Verleihen", "An wen, zurück bis, Notiz; Namen zum Antippen", "rechner", 4],
  ["r59-ausgaben-und-wert.html", "R59", "Ausgaben und Wert", "Ausgaben je Monat, Bestandswert, Preisverlauf", "rechner", 4],
  ["r55-foto-erkennen.html", "R55", "Foto erkennen", "Gespeicherte Fotos wählen, weitere nur zum Erkennen dazu", "rechner", 4],
  ["r54-inhalt-ansichten.html", "R54", "Inhalt als Liste und kompakt", "Ansicht, Filter, Sortierung und Archiv über dem Inhalt", "rechner", 4],
  ["r53-verkauf-liste.html", "R53", "Verkauf", "Offene Verkäufe: Entwürfe und eingestellte Anzeigen", "rechner", 4],
  ["r52-zuletzt-bewegt.html", "R52", "Zuletzt bewegt", "Bewegungen des Haushalts als Tabelle, in der Seitenleiste", "rechner", 4],
  ["r51-fotos-anlegen.html", "R51", "Fotos anlegen", "Mehrere Bilder nacheinander: neu, hinzufügen oder ablegen", "rechner", 4],
  ["r50-geloescht.html", "R50", "Zuletzt gelöscht", "Löschvorgänge wiederherstellen, erreichbar von der Ablage", "rechner", 4],
  ["r49-fuellstand.html", "R49", "Füllstand", "Pegel angebrochener Packungen ziehen oder mit Pfeiltasten schieben", "rechner", 4],
];

const STAFFELN = {
  1: "Staffel 1: Fundament, Anmeldung, Lager, Eintrag, Anlegen, Bewegen, Bearbeiten, Löschen",
  2: "Staffel 2: Mengen, Scanner, Listen, Katalog, Kategorien, Fotos",
  3: "Staffel 3: Anreichern, KI, Vorgänge, Wiegen, Hilfe, Einstellungen, Verwaltung, Etiketten, Verkauf",
  4: "Staffel 4: Zurückgestelltes, je Stück eine Seite",
};

if (typeof module !== "undefined" && module.exports) module.exports = { SEITEN, STAFFELN };
if (typeof window !== "undefined") { window.SEITEN = SEITEN; window.STAFFELN = STAFFELN; }
